igorwojda/android-showcase

.circleci/config.yml

Fix `java.util.ConcurrentModificationException`

Disable parallel lint execution

---

buildSrc/src/main/kotlin/CommonModuleDependency.kt
buildSrc/src/main/kotlin/CoreVersion.kt
buildSrc/src/main/kotlin/GradleDependency.kt
buildSrc/src/main/kotlin/LibraryDependency.kt
buildSrc/src/main/kotlin/TestLibraryDependency.kt

Updated dependency versions
Unified coroutine dependency version

Updated dependency versions

---

app/build.gradle.kts
app/src/main/java/com/igorwojda/showcase/AppModule.kt

Share Gradle properties by using `buildConfigField`, instead of `resValue`
See: https://developer.android.com/studio/build/gradle-tips#share-custom-fields-and-resource-values-with-your-app-code

Improve build params resValue -> buildConfigField

---

.editorconfig
app/src/main/java/com/igorwojda/showcase/app/feature/FeatureManager.kt
app/src/main/java/com/igorwojda/showcase/app/feature/KodeinModuleProvider.kt
feature_album/src/main/java/com/igorwojda/showcase/feature/album/FeatureKodeinModule.kt
feature_favourite/src/main/java/com/igorwojda/showcase/feature/favourite/FeatureKodeinModule.kt
feature_profile/src/main/java/com/igorwojda/showcase/feature/profile/FeatureKodeinModule.kt

`indent_size = 4` is default option nowdays for `ktlint`

Remove indent_size setting

---

app/src/main/java/com/igorwojda/showcase/app/presentation/NavHostActivity.kt
feature_album/src/main/java/com/igorwojda/showcase/feature/album/presentation/AlbumPresentationModule.kt
feature_album/src/main/java/com/igorwojda/showcase/feature/album/presentation/albumdetail/AlbumDetailFragment.kt
feature_album/src/main/java/com/igorwojda/showcase/feature/album/presentation/albumdetail/AlbumDetailViewModel.kt
feature_album/src/main/java/com/igorwojda/showcase/feature/album/presentation/albumlist/AlbumListFragment.kt
feature_album/src/main/java/com/igorwojda/showcase/feature/album/presentation/albumlist/AlbumListViewModel.kt
feature_album/src/main/java/com/igorwojda/showcase/feature/album/presentation/albumlist/recyclerview/AlbumAdapter.kt
feature_favourite/src/main/java/com/igorwojda/showcase/feature/favourite/presentation/favourite/FavouriteFragment.kt
feature_profile/src/main/java/com/igorwojda/showcase/feature/profile/presentation/profile/ProfileFragment.kt
library_base/src/main/AndroidManifest.xml
library_base/src/main/java/com/igorwojda/showcase/base/presentation/viewmodel/BaseAction.kt
library_base/src/main/java/com/igorwojda/showcase/base/presentation/viewmodel/BaseViewState.kt
library_base/src/main/java/com/igorwojda/showcase/library/base/delegate/Observer.kt
library_base/src/main/java/com/igorwojda/showcase/library/base/di/KotlinViewModelProvider.kt
library_base/src/main/java/com/igorwojda/showcase/library/base/presentation/activity/BaseActivity.kt
library_base/src/main/java/com/igorwojda/showcase/library/base/presentation/activity/InjectionActivity.kt
library_base/src/main/java/com/igorwojda/showcase/library/base/presentation/extension/BundleExtension.kt
library_base/src/main/java/com/igorwojda/showcase/library/base/presentation/extension/ContextExtensions.kt
library_base/src/main/java/com/igorwojda/showcase/library/base/presentation/extension/LiveDataExtensions.kt
library_base/src/main/java/com/igorwojda/showcase/library/base/presentation/extension/MutableLiveDataExtension.kt
library_base/src/main/java/com/igorwojda/showcase/library/base/presentation/extension/ViewExtensions.kt
library_base/src/main/java/com/igorwojda/showcase/library/base/presentation/fragment/BaseContainerFragment.kt
library_base/src/main/java/com/igorwojda/showcase/library/base/presentation/fragment/InjectionFragment.kt
library_base/src/main/java/com/igorwojda/showcase/library/base/presentation/viewmodel/BaseAction.kt
library_base/src/main/java/com/igorwojda/showcase/library/base/presentation/viewmodel/BaseViewModel.kt
library_base/src/main/java/com/igorwojda/showcase/library/base/presentation/viewmodel/BaseViewState.kt
library_base/src/main/java/com/igorwojda/showcase/library/base/presentation/viewmodel/StateTimeTravelDebugger.kt

Moved classes to the proper package `com.igorwojda.showcase.library.base`

Updated base library package

---

buildSrc/src/main/kotlin/AndroidConfig.kt

fix build type "debug" spell issue

[Shuai] fix build type spell issue

---

build.gradle

Because we added rootProject into settings.gradle.kts.

Remove build.gradle file

---

build.gradle.kts
feature_album/build.gradle.kts
feature_favourite/build.gradle.kts
feature_profile/build.gradle.kts

Related issue: https://github.com/JLLeitschuh/ktlint-gradle/issues/266

Proper filtering of navigation generated sources.

---

buildSrc/src/main/kotlin/TestLibraryDependency.kt
feature_album/src/test/java/com/igorwojda/showcase/feature/album/data/model/AlbumDataModelKtTest.kt
feature_album/src/test/java/com/igorwojda/showcase/feature/album/data/model/AlbumImageDataModelKtTest.kt
feature_album/src/test/java/com/igorwojda/showcase/feature/album/data/model/AlbumWikiDataModelKtTest.kt
feature_album/src/test/java/com/igorwojda/showcase/feature/album/data/repository/AlbumRepositoryImplTest.kt
feature_album/src/test/java/com/igorwojda/showcase/feature/album/domain/model/AlbumDomainModelTest.kt
feature_album/src/test/java/com/igorwojda/showcase/feature/album/domain/usecase/GetAlbumListUseCaseTest.kt
feature_album/src/test/java/com/igorwojda/showcase/feature/album/presentation/AlbumListViewModelTest.kt

- Updated ktlint `shouldEqual` to `shouldBeEqualTo`
- Updated ktlint version

Updated ktlint version and assertions

---

buildSrc/src/main/kotlin/LibraryDependency.kt
library_base/build.gradle.kts

Fixed a typo mistake on appcompat library.

Fix appcompat spell issue

---

app/src/main/java/com/igorwojda/showcase/AppModule.kt
feature_album/src/main/java/com/igorwojda/showcase/feature/album/FeatureKodeinModule.kt
feature_album/src/main/java/com/igorwojda/showcase/feature/album/data/AlbumDataModule.kt
feature_album/src/main/java/com/igorwojda/showcase/feature/album/domain/AlbumDomainModule.kt
feature_album/src/main/java/com/igorwojda/showcase/feature/album/presentation/AlbumPresentationModule.kt
feature_favourite/src/main/java/com/igorwojda/showcase/feature/favourite/FeatureKodeinModule.kt
feature_favourite/src/main/java/com/igorwojda/showcase/feature/favourite/data/FavouriteDataModule.kt
feature_favourite/src/main/java/com/igorwojda/showcase/feature/favourite/domain/FavouriteDomainModule.kt
feature_favourite/src/main/java/com/igorwojda/showcase/feature/favourite/presentation/FavouritePresentationModule.kt
feature_profile/src/main/java/com/igorwojda/showcase/feature/profile/FeatureKodeinModule.kt
feature_profile/src/main/java/com/igorwojda/showcase/feature/profile/data/ProfileDataModule.kt
feature_profile/src/main/java/com/igorwojda/showcase/feature/profile/domain/ProfileDomainModule.kt
feature_profile/src/main/java/com/igorwojda/showcase/feature/profile/presentation/ProfilePresentationModule.kt

Rename module name variable

---

buildSrc/src/main/kotlin/LibraryDependency.kt
library_base/src/main/java/com/igorwojda/showcase/library/base/presentation/activity/InjectionActivity.kt
library_base/src/main/java/com/igorwojda/showcase/library/base/presentation/fragment/InjectionFragment.kt

- Retrieve `kodeinTrigger` using lazy delegate
- Make all overrides `KodeinAware` members final
- upgrade kodein version to 6.55

Improve kodein setup

---

gradle.properties

Nowadays this is a default tooling (#96)

Remove deprecated R8 setting

---

app/src/main/kotlin/com/igorwojda/showcase/app/presentation/NavHostActivity.kt
feature_album/src/main/kotlin/com/igorwojda/showcase/feature/album/presentation/albumdetail/AlbumDetailFragment.kt
feature_album/src/main/kotlin/com/igorwojda/showcase/feature/album/presentation/albumlist/AlbumListFragment.kt
feature_favourite/src/main/kotlin/com/igorwojda/showcase/feature/favourite/presentation/favourite/FavouriteFragment.kt
feature_profile/src/main/kotlin/com/igorwojda/showcase/feature/profile/presentation/profile/ProfileFragment.kt

This reverts commit 3347d595b8595b30d23805745d63dcbafce44ceb.

Revert "Add view bindings delegate"

---

app/src/main/kotlin/com/igorwojda/showcase/app/presentation/NavHostActivity.kt

Do not allow to select the same menu item again (and recreate the fragment)
Closes #107

Fix menu reselection

---

.github/workflows/update-dependencies.yml

Runs every week and creates PR

Add automated dependency update workflow

---

app/src/main/kotlin/com/igorwojda/showcase/app/presentation/NavHostActivity.kt

Closes #54
More:
https://medium.com/@ffvanderlaan/fixing-the-dreaded-is-unknown-to-this-navcontroller-68c4003824ce

Fix unknown destination crash

---

README.md

This PR updates the link for Kodein docs from `https://kodein.org/Kodein-DI/` --to--> `https://docs.kodein.org/`

Update Readme Kodein docs link

---

feature_album/src/main/kotlin/com/igorwojda/showcase/feature/album/domain/usecase/GetAlbumListUseCase.kt
feature_album/src/main/kotlin/com/igorwojda/showcase/feature/album/domain/usecase/GetAlbumUseCase.kt
feature_album/src/main/kotlin/com/igorwojda/showcase/feature/album/presentation/screen/albumdetail/AlbumDetailViewModel.kt
feature_album/src/main/kotlin/com/igorwojda/showcase/feature/album/presentation/screen/albumlist/AlbumListViewModel.kt
feature_album/src/test/kotlin/com/igorwojda/showcase/feature/album/domain/usecase/GetAlbumListUseCaseTest.kt
feature_album/src/test/kotlin/com/igorwojda/showcase/feature/album/domain/usecase/GetAlbumUseCaseTest.kt
feature_album/src/test/kotlin/com/igorwojda/showcase/feature/album/presentation/screen/albumdetail/AlbumDetailViewModelTest.kt
feature_album/src/test/kotlin/com/igorwojda/showcase/feature/album/presentation/screen/albumlist/AlbumListViewModelTest.kt

Neat little trick I learned from google best practises https://developer.android.com/kotlin/coroutines/coroutines-best-practices
Since usecases have only 1 method I think it makes sense to do like this

Use operator in useCase

---

app/src/main/java/com/igorwojda/showcase/app/presentation/NavHostActivity.kt
app/src/main/res/drawable-v24/ic_search.xml
app/src/main/res/layout/activity_nav_host.xml
feature_album/src/main/kotlin/com/igorwojda/showcase/feature/album/data/datasource/api/service/AlbumRetrofitService.kt
feature_album/src/main/kotlin/com/igorwojda/showcase/feature/album/data/repository/AlbumRepositoryImpl.kt
feature_album/src/main/kotlin/com/igorwojda/showcase/feature/album/domain/repository/AlbumRepository.kt
feature_album/src/main/kotlin/com/igorwojda/showcase/feature/album/domain/usecase/GetAlbumListUseCase.kt
feature_album/src/main/kotlin/com/igorwojda/showcase/feature/album/presentation/screen/albumlist/AlbumListFragment.kt
feature_album/src/main/kotlin/com/igorwojda/showcase/feature/album/presentation/screen/albumlist/AlbumListViewModel.kt
feature_album/src/main/res/values/strings.xml
feature_album/src/test/kotlin/com/igorwojda/showcase/feature/album/domain/usecase/GetAlbumListUseCaseTest.kt
feature_album/src/test/kotlin/com/igorwojda/showcase/feature/album/presentation/screen/albumlist/AlbumListViewModelTest.kt
feature_base/src/main/kotlin/com/igorwojda/showcase/base/presentation/activity/BaseActivity.kt
feature_base/src/main/kotlin/com/igorwojda/showcase/base/presentation/ext/ViewExt.kt
feature_base/src/main/res/drawable/ic_search.xml
feature_base/src/main/res/menu/menu_toolbar_main.xml
feature_base/src/main/res/values/strings.xml
feature_base/src/main/res/values/styles.xml

Added the ability to make album searchs from the appbar

Added the feature to search albums from appbar

---

feature_album/src/main/kotlin/com/igorwojda/showcase/feature/album/presentation/screen/albumlist/AlbumListFragment.kt
feature_album/src/main/res/menu/menu_toolbar_main.xml
feature_base/src/main/kotlin/com/igorwojda/showcase/base/presentation/ext/ViewExt.kt

Commit 1 Fixes https://github.com/igorwojda/android-showcase/issues/351 
Commit 2 Fixes https://github.com/igorwojda/android-showcase/issues/352

Do Search on Enter key

---

konsist_test/src/test/kotlin/com/igorwojda/showcase/konsisttest/GeneralKonsistTest.kt

Add missing @Test annotation in the `no empty files allowed` test function.

Add @Test annotation

---

README.md
buildLogic/src/main/kotlin/com/igorwojda/showcase/buildlogic/ApplicationConventionPlugin.kt
buildLogic/src/main/kotlin/com/igorwojda/showcase/buildlogic/FeatureConventionPlugin.kt
gradle/libs.versions.toml

- Remove `livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }`
- Clean up dependencies

Clean Up Depdndencies

---

README.md
gradle.properties

https://docs.gradle.org/9.0.0/userguide/configuration_cache_enabling.html

Enable Gradle Configuration Cache
